const data ={
    product:[ 
        {names:'Nike slim shirt,',
        slug:'Nike-Slim-Shirt',
        catagory:'Shirts',
        image:'/my-react-app/images/download.jpg',
        price:120,
        countInStock:20,
        bramd: 'Nike',
        rating:4.4,
        numReview:10,
        description:'high quality product shirt',
        },
        {names:'Nike slim shirt,',
        slug:'Nike-Slim-Shirt',
        catagory:'Shirts',
        image:'/my-react-app/images/download.jpg',
        price:120,
        countInStock:20,
        bramd: 'Nike',
        rating:4.4,
        numReview:10,
        description:'high quality product shirt',
        },
        {names:'Nike slim shirt,',
        slug:'Nike-Slim-Shirt',
        catagory:'Shirts',
        image:'/my-react-app/images/download.jpg',
        price:120,
        countInStock:20,
        bramd: 'Nike',
        rating:4.4,
        numReview:10,
        description:'high quality product shirt',
        },
        {names:'Nike slim shirt,',
        slug:'Nike-Slim-Shirt',
        catagory:'Shirts',
        image:'/my-react-app/images/download.jpg',
        price:120,
        countInStock:20,
        bramd: 'Nike',
        rating:4.4,
        numReview:10,
        description:'high quality product shirt',
        },
    ],
};
export default data;